language: python
python:
  - "2.7"

env:
  global:
    # encrypted $OAUTH_REFRESH_TOKEN needed for deployment
    secure: "RwbmRKMqzHkDB1kaurFLOVYLS2mnYp+IXHNIGvziTjl8x2ccKs568clPu/nNdlQKqbUlvPhlM/Nr7SHF/GV2SWE2unq2Bjn9/WA3dNVL/PsMmfvJbZ0pnepDKFc/YhKf37uYQQWWwzfLo11iOLkcDWFsZ15tWoMXK2VjZkPbKBw="
virtualenv:
  system_site_packages: true

before_install:
  - npm install -g casperjs
install: "pip install -r requirements.txt"

before_script:
  - cd ..
  - wget https://storage.googleapis.com/appengine-sdks/deprecated/195/google_appengine_1.9.5.zip -nv
  - unzip -q google_appengine_1.9.5.zip
  - export SDK_LOCATION="$(pwd)/google_appengine"
  - cd $TRAVIS_BUILD_DIR
  - git fetch --tags
  - python deploy.py --generate-only --generate-test 1000
  - python $SDK_LOCATION/dev_appserver.py --skip_sdk_update_check 1 . &
  - sleep 10
script: python travis.py

after_success: python deploy.py
